services:
  - type: web
    name: neon-flap
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: neon-flap-db
          property: connectionString

databases:
  - name: neon-flap-db
    databaseName: neonflap
    plan: free
